language: python
python:
    - '3.8'

install:
    - pip install -r requirements-dev.txt

env:
    - PYTHONPATH=/home/travis/build/meishinlee/SWE-Team

script:
    - make tests

# deploy to heroku on push to master
deploy:
    - provider: heroku
      api_key: 901d1995-0d67-4a96-86ce-8fab4ab75adf
      app: swe-team
      on:
          branch: master